#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

struct EtherCrabOption {
  const char* ifname;
  Duration dc_configuration_sync0_period;
  Duration state_check_period;
  Duration sync_tolerance;
  Duration sync_timeout;
};

extern "C" {

[[nodiscard]]
ResultLink AUTDLinkEtherCrab(const void* err_handler, const void* err_context, EtherCrabOption option);

[[nodiscard]] bool AUTDLinkEtherCrabIsDefault(EtherCrabOption option);

[[nodiscard]] uint32_t AUTDLinkEtherCrabStatusGetMsg(Status src, char* dst);

}  // extern "C"

}  // namespace autd3::native_methods
