#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

/// The status of the EtherCAT device.
enum class Status : uint8_t {
  /// The device is in SAFE-OP + ERROR.
  Error = 0,
  /// The device is lost.
  Lost = 1,
  /// The device is in SAFE-OP.
  StateChanged = 2,
  /// All devices resumed OP.
  Resumed = 4,
};

}  // namespace autd3::native_methods
